@startuml
title 勤怠管理アプリ

entity Employee {
  + employee_id : int
  --
  name : string
  role : integer(enum)
  password_digest : string
  manager_id : int
  paid_holiday_count : int
}
Employee ||--o{ Employee : manager

entity EmployeeRule {
  + rule_id : int
  --
  employee_id : int
  holiday_work? : bool
  core_time_start : time
  core_time_end : time
  break_time_minutes : int
}

Employee ||--||EmployeeRule

entity Attendance {
  + attendance_id : int
  --
  employee_id : int
  day : date
  status : integer(enum)
  started_at : datetime
  finished_at : datetime
  break_minutes : integer
  
}

entity AttendanceEditRequest{
  + request_id : int
  --
  employee_id : int
  approve_manager_id : int
  status : integer(enum)
  edit_type : integer(enum)
  modify_time_start : time
  modify_time_end : time
}

entity LeaveRequest{
  + request_id : int
  --
  employee_id : int
  approve_manager_id : int
  status : integer(enum)
  leave_type : integer(enum)
  start_date : date
  end_date : date
}

Employee ||--o{ Attendance
Employee ||--o{ LeaveRequest
Attendance ||--o{ AttendanceEditRequest


@enduml